# Uncomment the next line to define a global platform for your project
#source 'https://cdn.cocoapods.org/'
#source 'https://github.com/track-asia/trackasia-flutter-podspecs.git'
platform :ios, '15.0'

target 'TrackAsiaDemo' do
  use_frameworks!

pod 'Alamofire'
  
end

